
export const GET_All_DATA ="GET_All_DATA";
export const GET_DATA_SUCCESS='GET_DATA_SUCCESS';

export const GET_All_ACTION ="GET_All_ACTION";
export const GET_All_ACTION_SUCCESS='GET_All_ACTION_SUCCESS';

export const GET_LIST_OPERATION_ACTION="GET_LIST_OPERATION_ACTION";
export const GET_LIST_OPERATION_SUCCESS='GET_LIST_OPERATION_SUCCESS';